"""
Handling HTML response serving contents generated by tanstack (https://github.com/tanstack/router).
Notably used by X (formerly Twitter)
"""
"""
MIT License

Copyright (c) 2026 t-wy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

from typing import *

if TYPE_CHECKING:
    import io

def parse_html(html: str) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
    from bs4 import BeautifulSoup
    soup = BeautifulSoup(html, 'html.parser')
    # get #$tsr-stream-barrier
    # script = soup.find('script', id='$tsr-stream-barrier').decode_contents()
    # script_start = 'class="$tsr" id="$tsr-stream-barrier">'
    # assert script_start in html
    # script = html.split(script_start, 1)[1]
    matches = []
    records = []
    for script in soup.find_all('script'):
        content: str = script.text
        record_salt = ']={relayRecords:'
        if record_salt not in content:
            continue
        if script.get('id') == '$tsr-stream-barrier':
            router_start = '$_TSR.router=($R=>$R[0]='
            assert router_start in content
            router = content.split(router_start, 1)[1]
            import io
            reader = io.StringIO(router)
            content = parse_js_dict(reader)[0]
            matches = content.get("matches", [])
            record = hydrate(content.get("dehydratedData", {}).get("relayRecords", {}))
            records.append(record)
        else:
            assert record_salt in content
            record_content = '{relayRecords:' + content.split(record_salt, 1)[1]
            import io
            reader = io.StringIO(record_content)
            content = parse_js_dict(reader)[0]
            records.append(hydrate(content.get("relayRecords", {})))
    return matches, records

def peek(reader: "io.StringIO", size: int):
    pos = reader.tell()
    temp = reader.read(size)
    reader.seek(pos)
    return temp

def skip_space(reader: "io.StringIO"):
    while peek(reader, 1) in ' \t\n':
        reader.read(1)

def hydrate(relayRecords: Dict[str, Any]) -> Dict[str, Any]:
    def hydrate_internal(content: Dict[str, Any]):
        if isinstance(content, dict):
            if "__id" in content:
                del content["__id"]
            for key, value in content.items():
                if isinstance(value, dict) and len(value) == 1:
                    if "__ref" in value:
                        content[key] = relayRecords[value["__ref"]]
                        continue
                    elif "__refs" in value:
                        content[key] = [ relayRecords[ref] for ref in value["__refs"] ]
                        continue
                hydrate_internal(value)
        elif isinstance(content, list):
            for value in content:
                hydrate_internal(value)
    for value in relayRecords.values():
        hydrate_internal(value)
    return relayRecords["client:root"]

letters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
valid_start_characters = letters + "_$"
numbers = "0123456789"
valid_characters = valid_start_characters + numbers
def parse_name(reader: "io.StringIO") -> str:
    c = reader.read(1)
    assert c in valid_start_characters, f"Expected valid start character, got {c!r} at position {reader.tell() - 1} (After: {reader.read(10)})"
    result = [ c ]
    while peek(reader, 1) in valid_characters:
        result.append(reader.read(1))
    return "".join(result)

def parse_number(reader: "io.StringIO") -> int:
    c = reader.read(1)
    assert c in numbers, f"Expected numeric character, got {c!r} at position {reader.tell() - 1} (After: {reader.read(10)})"
    result = [ c ]
    while peek(reader, 1) in numbers:
        result.append(reader.read(1))
    return int("".join(result))

def parse_string(reader: "io.StringIO") -> str:
    assert_next_character(reader, '"')
    result = [ '"' ]
    escape = False
    while True:
        if escape:
            result.append(reader.read(1))
            escape = False
        else:
            c = reader.read(1)
            if c == "\0":
                result.append("\\u0000")
            else:
                result.append(c)
            if c == '"':
                break
            elif c == '\\':
                escape = True
    import json
    return json.loads("".join(result))

def parse_name_or_string(reader: "io.StringIO") -> str:
    c = peek(reader, 1)
    if c == '"':
        return parse_string(reader)
    else:
        return parse_name(reader)

def parse_boolean(reader: "io.StringIO") -> str:
    assert_next_character(reader, '!')
    content = reader.read(1)
    assert content in ['0', '1']
    if content == "0":
        return True # !0
    return False # !1

def parse_js_object(reader: "io.StringIO", R: Dict[int, Any] = {}):
    c = peek(reader, 1)
    if c == '{':
        return parse_js_dict(reader, R = R)
    elif c == '[':
        return parse_js_array(reader, R = R)
    elif c == 'v':
        assert_next_character(reader, 'void 0')
        return None, False
    elif c == 'n':
        assert_next_character(reader, 'null')
        return None, False
    elif c == '$':
        assert_next_character(reader, '$R[')
        idx = parse_number(reader)
        assert_next_character(reader, ']')
        c2 = peek(reader, 1)
        if c2 == "=":
            assert_next_character(reader, '=')
            temp = parse_js_object(reader, R = R)
            R[idx] = temp
            return temp
        elif c2 in (',', '}', ']'): # ending
            return R[idx], False
    elif c == '"':
        return parse_string(reader), False
    elif c in numbers:
        return parse_number(reader), False
    elif c == '!':
        return parse_boolean(reader), False
    elif c == '(':
        # the start of something like $R[61]=($R[62]=(stream) => new ReadableStream({ start(controller) {
        assert_next_character(reader, '($R[')
        return ..., True
    else:
        assert False, f"Unexpected character {c!r} at position {reader.tell()} (After: {reader.read(10)})"

def assert_next_character(reader: "io.StringIO", expected: str):
    next_c = reader.read(len(expected))
    assert next_c == expected, f"Expected {expected!r}, got {next_c!r} at position {reader.tell() - 1} (After: {reader.read(10)})"

def parse_js_dict(reader: "io.StringIO", R: Dict[int, Any] = {}) -> Tuple[Dict[str, Any], bool]:
    assert_next_character(reader, '{')
    result = {}
    skip_space(reader)
    if peek(reader, 1) == '}':
        # empty dict
        assert_next_character(reader, ']')
        return result, False
    while True:
        key = parse_name_or_string(reader)
        skip_space(reader)
        assert_next_character(reader, ':')
        skip_space(reader)
        value, shutdown = parse_js_object(reader, R = R)
        if shutdown:
            if value is not ...:
                result[key] = value
            return result, True
        result[key] = value
        skip_space(reader)
        if peek(reader, 1) == '}':
            break
        assert_next_character(reader, ',')
    assert_next_character(reader, '}')
    return result, False

def parse_js_array(reader: "io.StringIO", R: Dict[int, Any] = {}) -> Tuple[list, bool]:
    assert_next_character(reader, '[')
    result = []
    skip_space(reader)
    if peek(reader, 1) == ']':
        # empty array
        assert_next_character(reader, ']')
        return result, False
    while True:
        skip_space(reader)
        value, shutdown = parse_js_object(reader, R = R)
        if shutdown:
            if value is not ...:
                result.append(value)
            return result, True
        result.append(value)
        skip_space(reader)
        if peek(reader, 1) == ']':
            break
        assert_next_character(reader, ',')
    assert_next_character(reader, ']')
    return result, False

if __name__ == "__main__":
    import sys
    with open("_temp/tweet.html" if len(sys.argv) < 2 else sys.argv[1]) as f:
        parsed = parse_html(f.read())
        try:
            import json
            print(json.dumps(parsed, indent = 4, ensure_ascii = False))
        except:
            print(parsed)