from discord.app_commands import locale_str as _

# Common Texts used in App Commands (Command Names / Option Names)

class description:
    accessory_name = _('Accessory name', zh="飾品名稱", ja="アクセサリー名")
    accessory_mode = _('The item to fetch', zh="飾品資訊", ja="アクセサリー情報")
    all_ticks = _("Show hidden ticks", zh="顯示隱藏節點")
    another_notation = _('Use another notation', zh="使用其他譜面", ja="アナザー譜面の使用")
    asset_name = _('Asset name', zh="素材名稱", ja="アセット名")
    bar_mode = _("Show bars instead of seconds", zh="顯示小節而非秒數")
    bar_mode_experimental = _("Show bars instead of seconds (Experimental)", zh="顯示小節而非秒數 (測試中)")
    card_name = _('Card name', zh="卡面名稱", ja="カード名")
    card_mode = _('The item to fetch', zh="卡面資訊", ja="カード情報")
    character = _('Character Name', zh="角色名稱", ja="キャラクター名")
    character_info = _("Character Basic Information", zh="角色基本資料", ja="キャラクター設定")
    diff = _('Chart difficulty', zh="譜面難度", ja="譜面難易度")
    event_borders = _("Event ranking borders", zh="活動排名榜線", ja="イベントボーダー")
    event_info = _("Event information", zh="活動資訊", ja="イベント情報")
    event_name = _('Event name', zh="活動名稱", ja="イベント名")
    human_readable_size=_('Use file size units', zh="使用檔案大小單位")
    mirror = _('Mirror mode', zh="鏡像模式", ja="ミラーモード")
    next_rank = _("Rankings 1 lower than each border", zh="榜線下一名的數字")
    def rank(max: int):
        return _('Target rank (1 ~ {})'.format(max), zh="目標排名 (1 至 {})".format(max), ja="目標順位 (1 ～ {})".format(max))
    player_id = _('Player id', zh="玩家 ID", ja="プレイヤー ID")
    poster_name = _('Poster name', zh="海報名稱", ja="ポスター名")
    poster_mode = _('The item to fetch', zh="海報資訊", ja="ポスター情報")
    reencode_audio = _("Reencode the audio file so that it does not take up much space", zh="重新編碼音檔以使其能佔據較小空間")
    reencode_video = _("Reencode the video file so that it is preview-able", zh="重新編碼影片以使其能被預覽")
    reencode = _("Reencode the file so that it can be sent and viewed", zh="重新編碼內容以使其能被傳送及預覽")
    score = _('Score', zh="分數", ja="スコア")
    secsep = _('No. of seconds per column (Default: 10)', zh="每行顯示秒數 (預設: 10)")
    show_name = _("Display player names", zh="顯示玩家名稱")
    songname = _('Song name', zh="歌曲名稱", ja="曲名")
    version_asset = _("Asset version", zh="資源版本", ja="アセットバージョン")

class locale:
    accessory = _('accessory', zh="飾品", ja="アクセサリー")
    all_ticks = _("all_ticks", zh="全節點")
    another_notation = _('another_notation', zh="其他譜面", ja="アナザー譜面")
    asset_name = _('asset_name', zh="素材名稱", ja="アセット名")
    bar_mode = _("bar_mode", zh="小節模式")
    card = _('card', zh="卡面", ja="カード")
    character = _("character", zh="角色", ja="キャラクター")
    detail = _("detail", zh="詳細", ja="詳細")
    diff = _("diff", zh="難度", ja="難易度")
    event_borders = _("event_borders", zh="活動榜線", ja="イベントボーダー")
    event_name = _('event_name', zh="活動名稱", ja="イベント名")
    info = _("info", zh="資訊", ja="情報")
    latest = _('latest', zh="最近", ja="最近")
    mirror = _("mirror", zh="鏡像", ja="ミラー")
    mode = _("mode", zh="模式", ja="モード")
    name = _('name', zh="名稱", ja="名")
    next_rank = _("next_rank", zh="下一名", ja="次の順位")
    poster = _('poster', zh="海報", ja="ポスター")
    rank = _('rank', zh="排名", ja="順位") # as field name
    ranking = _("ranking", zh="排名", ja="ランキング") # as group name
    reencode = _("reencode", zh="重新編碼")
    score = _('score', zh="分數", ja="スコア")
    secsep = _('secsep', zh="秒數分隔")
    songname = _("song_name", zh="歌名", ja="曲名")
    show_name = _("show_name", zh="顯示名稱")
    version = _("version", zh="版本", ja="バージョン")