from locale_str import locale_str_ex as _

# Common Texts used in App Commands (Group Names / Command Names / Option Names)

class description:
    accessory_info = _("Accessory information", zh="飾品資訊")
    accessory_name = _('Accessory name', zh="飾品名稱", ja="アクセサリー名")
    accessory_mode = _('The item to fetch', zh="飾品資訊", ja="アクセサリー情報")
    all_ticks = _("Show hidden ticks", zh="顯示隱藏節點")
    another_notation = _('Use another notation', zh="使用其他譜面", ja="アナザー譜面の使用")
    api_info = _("Get api information", zh="取得遊戲 api 的資訊")
    asset_background_images = _("All background images", zh="所有背景圖")
    asset_name = _('Asset name', zh="素材名稱", ja="アセット名")
    asset_posters = _("All posters", zh="所有海報")
    asset_song_jackets = _("All song jackets", zh="所有歌曲封面")
    asset_stamps = _("All stamps", zh="所有貼圖")
    audition = _("Audition-related information", zh="試鏡資訊")
    audio_video = _("Game audio / video", zh="遊戲音訊及影片")
    bar_mode = _("Show bars instead of seconds", zh="顯示小節而非秒數")
    bar_mode_experimental = _("Show bars instead of seconds (Experimental)", zh="顯示小節而非秒數 (測試中)")
    bpm_search = _("Search Songs with Specified BPM.", zh="尋找對應 BPM 的歌曲")
    by_rank = _('True: by rank, False: by player', zh="True：追蹤指定排名、False：追蹤當前玩家", ja="True：同順位の推移・False：同プレイヤーの推移")
    card_info = _("Card information", zh="卡面資訊")
    card_name = _('Card name', zh="卡面名稱", ja="カード名")
    card_mode = _('The item to fetch', zh="卡面資訊", ja="カード情報")
    card_rarity = _('Card rarity', zh="卡面稀有度")
    campaign = _("Campaign information", zh="Campaign 資訊")
    character = _('Character Name', zh="角色名稱", ja="キャラクター名")
    character_event_chart = _("Character Event ranking chart", zh_TW="角色活動排名走勢圖", zh_CN="角色活动排名走势图", ja="応援イベントランキング推移グラフ")
    character_event_pt = _('Character Event Single play point', zh="角色榜一場得分", ja="応援イベント1プレイの得点")
    character_info = _("Character Basic Information", zh="角色基本資料", ja="キャラクター設定")
    circle_id = _('Circle id', zh_TW="社團 ID", zh_CN="社团 ID", ja="サークル ID")
    count_card = _('Number of cards', zh="卡面數量")
    cover_songs_guess = _('Whether to include cover songs', zh="是否顯示翻唱曲", ja="カバー曲表示") # vs pre_existing_songs_guess
    detail_circle = _("Detailed circle information", zh="詳細社團資訊")
    detail_player = _("Detailed player information", zh="詳細玩家資訊")
    diff = _('Chart difficulty', zh="譜面難度", ja="譜面難易度")
    diff_command = _("Basic Information Regarding Song Difficulty", zh="譜面難度基本資訊")
    diff_guess = _('Specify difficulty (Amount of hint)', zh="指定題目難度（提示數量）")
    diff_guess_song = _('Specify difficulty (Trimmed Duration)', zh="指定題目難度（剪輯秒數）")
    diff_summary = _("Summary between assets diff", zh="素材版本差異總結")
    diff_table = _("Image of sorted difficulty", zh="以難度排序的圖片")
    difference = _("Difference between assets", zh="素材版本間的差異")
    duration_command = _("List of Longest and Shortest songs", zh="最長與最短的歌曲列表", ja="長い曲と短い曲の一覧")
    efficient_songs_command = _("Most time-efficient songs", zh="時間效率最高的歌曲", ja="一番時間効率の高い曲")
    episode_theater = _('Theater No.', zh="劇場話數")


    event_active = _("No. of participants in an event.", zh="活動參加人數")
    event_active_character = _("No. of participants in the Per-Character rankings.", zh="個別角色活動排名參加人數")
    event_chart = _("Event ranking chart", zh="活動排名走勢圖", ja="イベントランキング推移グラフ")
    event_info = _("Event information", zh="活動資訊", ja="イベント情報")
    event_name = _('Event name', zh="活動名稱", ja="イベント名")
    event_pt = _('Single play point', zh="一場得分", ja="1プレイの得点")

    event_ranking = _("Rankings of an event.", zh="活動排名", ja="イベントランキング")
    event_ranking_character = _("Per-Character rankings of an event.", zh="個別角色活動排名", ja="キャラクター別イベントランキング")
    event_borders = _("Event ranking borders", zh="活動排名榜線", ja="イベントボーダー")
    event_ranking_borders_character = _("Per-Character borders of an event.", zh="個別角色活動榜線", ja="キャラクター別イベントボーダー")
    event_ranking_predict = _("Event ranking prediction", zh_TW="活動榜線預測", zh_CN="活动榜线预测", ja="イベントボーダー予測")
    event_ranking_predict_detail = _("Detailed event prediction", zh="詳細活動榜線預測")
    event_ranking_predict_detail_jiiku = _("Detailed event prediction from jiiku831", zh="來自 jiiku831 的詳細活動榜線預測")
    event_ranking_predict_detail_character = _("Detailed event character ranking prediction", zh="詳細活動角色榜線預測")
    event_ranking_predict_detail_character_jiiku = _("Event character ranking prediction from jiiku831", zh="來自 jiiku831 的角色活動榜線預測")
    event_song = _('Is Event Song', zh="活動歌曲")
    fps = _('Frame Rate (per second)', zh="每秒影格率")
    gacha_info = _("Gacha information", zh="卡池資訊", ja="ガチャ情報")
    gacha_name = _('Gacha Name', zh_TW="卡池名稱", zh_CN="卡池名称", ja="ガチャ名")
    gacha_spoiler = _("All unreleased gacha", zh="所有還沒開始的卡池", ja="全ての開催予定のガチャ")
    game_file = _("Game files", zh="遊戲檔案")
    grayscale = _('Show Grayscale Version', zh="顯示灰階處理後的封面")
    guess_jacket = _("Guess the song from the cropped jacket", zh="猜出封面的歌曲")
    guess_lyrics = _("Guess the song from the given lyrics", zh="猜出歌詞的歌曲")
    guess_silhouette = _("Guess the character in the silhouette", zh="猜出剪影的角色")
    guess_song = _("Guess the song from the given sample", zh="猜出樣本的歌曲")
    hidden_fields = _("Show hidden fields", zh="顯示隱藏欄位")
    human_readable_size=_('Use file size units', zh="使用檔案大小單位")
    keyboard = _('Keyboard Mode Scoreboard', zh="鍵盤組排名")
    keywords = _('Substring in the asset (separated by spaces)', zh="素材名稱出現的字串 (以空格分隔)")
    latest_batch_card = _("Latest card batch", zh="最新批卡面")
    latest_batch_poster = _("Latest poster batch", zh="最新批海報")
    list_ = _("All songs for certain version", zh="版本所有歌曲")
    lrc = _('Choose True to output as .lrc file', zh="如要輸出 .lrc 檔案，請選擇 True")
    lyrics = _("Game-version lyrics of songs.", zh="遊戲版本歌詞")
    master = _("Get master database", zh="取得 Master 資料庫的內容")
    master_diff = _("Get difference between master database", zh="取得 Master 資料庫之間的差異")
    merge = _('Merge 3 images (default: False)', zh="合併成一張圖片 (預設：False)")
    mirror = _('Mirror mode', zh="鏡像模式", ja="ミラーモード")
    next_rank = _("Rankings 1 lower than each border", zh="榜線下一名的數字")
    old_version_8_digits = _("Old game data version (8 digits)", zh="舊遊戲版本（8 位數）")
    only_me = _("Restrict others from using", zh="限制其他人使用")
    order_legacy = _('Release order (0: All)', zh="卡面推出次序 (0：全部)")
    order_0 = _('The release order of the card batch (0: All unreleased, 1: Latest)', zh="相關卡面的推出批次 (0 為所有未推出，1 為最近)")
    order_1 = _('The release order of the card batch (1: Latest)', zh="相關卡面的推出批次 (1 為最近)")
    order_0_poster = _('The release order of the card batch (0: All unreleased, 1: Latest)', zh="相關卡面的推出批次 (0 為所有未推出，1 為最近)")
    order_1_poster = _('The release order of the card batch (1: Latest)', zh="相關卡面的推出批次 (1 為最近)")
    ping = _("Test Connectivity", zh="連通確認", ja="疎通確認")
    player_id = _('Player id', zh="玩家 ID", ja="プレイヤー ID")
    player_info = _("Player information.", zh="玩家資訊")
    poster_info = _("Poster information", zh="海報資訊")
    poster_name = _('Poster name', zh="海報名稱", ja="ポスター名")
    poster_mode = _('The item to fetch', zh="海報資訊", ja="ポスター情報")
    pre_existing_songs_guess = _('Whether to include existing songs', zh="是否顯示既存曲", ja="既存曲表示") # vs cover_songs_guess
    @staticmethod
    def rank_range(max: int):
        return _('Target rank (1 ~ {})'.format(max), zh="目標排名 (1 至 {})".format(max), ja="目標順位 (1 ～ {})".format(max))
    @staticmethod
    def rank_from_range(max: int):
        return _('From rank (1 ~ {})'.format(max), zh="開始排名 (1 至 {})".format(max), ja="開始順位 (1 ～ {})".format(max))
    rank = _('Target rank', zh="目標排名")
    ranking_type = _('Ranking Type', zh="排名類型")
    recent_songs = _("Recent Songs", zh="最近追加歌曲")
    recent_vocal = _("Recent Vocals", zh="最近追加Vocal")
    reencode_audio = _("Reencode the audio file so that it does not take up much space", zh="重新編碼音檔以使其能佔據較小空間")
    reencode_video = _("Reencode the video file so that it is preview-able", zh="重新編碼影片以使其能被預覽")
    reencode = _("Reencode the file so that it can be sent and viewed", zh="重新編碼內容以使其能被傳送及預覽")
    reverse_guess = _('Reverse sample', zh="倒轉提供樣本")
    score = _('Score', zh="分數", ja="スコア")
    score_approx = _("Unit's Estimated Score", zh="隊伍大約分數", ja="編成のおおよそのスコア")
    score_command = _("Chart score approximation", zh="譜面的預測分數")
    @staticmethod
    def score_range(max: int):
        return _(f'Target score (0 ~ {max})', zh=f"目標積分 (0 至 {max})", ja="目標スコア (0 ～ {})".format(max))
    search = _("Search game assets", zh="搜尋遊戲資源")
    secsep = _('No. of seconds per column (Default: 10)', zh="每行顯示秒數 (預設: 10)")
    speed = _('Note fall speed', zh="譜面下落速度")
    spine = _("Include Spine Files", zh="包括 Spine 貼圖")
    song_chart = _("Chart image", zh="譜面圖片")
    song_chart_video = _("Chart Video", zh="譜面影片")
    song_diff_source = _("Statistic Source", zh="評價的來源")
    song_discover = _("Discover songs not in asset", zh="探索未出現在素材中的歌曲")
    song_info = _("Song basic information", zh="歌曲基本資訊")
    song_stat = _("Chart note distribution", zh="譜面的各項分布數據")
    sort_skill = _('Sort by the skills in the unit', zh="按隊伍成員的特技排序")
    story_raw = _("Obtain Unformatted Story in JSON", zh="取得 JSON 版本")
    show_distance = _("Show distance between every two notes", zh="顯示每兩個節奏圖示之間的距離")
    show_character = _("Show the character chosen", zh="顯示玩家選擇的角色")
    show_count = _('Show duplicate count', zh="顯示複製數量")
    show_lyrics = _('Show lyrics (Default: True)', zh="顯示歌詞 (預設為 True)")
    show_name = _("Display player names", zh="顯示玩家名稱")
    show_percentage = _("Show Corr. Clear Percentage", zh="顯示相關通關百分比")
    song_name = _('Song name', zh="歌曲名稱", ja="曲名")
    stage_audition = _("Audition Stage", zh="試鏡關卡")
    static = _("Get Static Asset URL", zh_TW="取得靜態資源的網址", zh_CN="取得静态资源的网址", ja="静的アセットのURLの取得")
    story = _("Game stories", zh="取得遊戲劇情")
    table_name = _("Table name", zh_TW="表格名稱", zh_CN="表格名称")
    type_campaign = _('Campaign type', zh="Campaign 的類型")
    unit_detail = _('Show skill info', zh_TW="顯示隊伍特技", zh_CN="显示队伍特技")
    unreleased = _("Include unreleased contents", zh_TW="包括未公開內容", zh_CN="包括未公开内容", ja="未公開内容を含む")
    ver_lang = _('Game Language Version', zh="語言版本")
    version_game = _("Get game version", zh_TW="取得遊戲版本", zh_CN="取得游戏版本", ja="ゲームバージョン")
    version_asset = _("Asset version", zh_TW="資源版本", zh_CN="资源版本", ja="アセットバージョン")
    witch = _('Keep witch notes', zh="保留Witch特效")
    zipped = _("Keep sending a zip file instead of separate files", zh_TW="維持發送一個壓縮檔而非獨立檔案", zh_CN="维持发送一个压缩档而非独立档案")

class locale:
    accessory = _('accessory', zh_TW="飾品", zh_CN="飾品", ja="アクセサリー")
    all_ticks = _("all_ticks", zh_TW="全節點", zh_CN="全节点")
    another_notation = _('another_notation', zh_TW="其他譜面", zh_CN="其他谱面", ja="アナザー譜面")
    api_info = _('api_info', zh_TW="api資訊", zh_CN="api资讯")
    asset = _("asset", zh="素材", ja="アセット")
    asset_name = _('asset_name', zh_TW="素材名稱", zh_CN="素材名称", ja="アセット名")
    audition = _("audition", zh_TW="試鏡", zh_CN="试镜", ja="オーディション")
    audio_video = _('audio_video', zh="影音")
    background_images = _('background_images', zh_TW="背景圖片", zh_CN="背景图片") # for asset command (implying plural)
    bar_mode = _("bar_mode", zh_TW="小節模式", zh_CN="小节模式")
    bpm_search = _("bpm_search", zh_TW="bpm搜尋", zh_CN="bpm搜索", ja="bpm検索")
    by_rank = _('by_rank', zh="按排名", ja="順位依存")
    card = _('card', zh="卡面", ja="カード") # as group name and argument name
    cards = _("cards", zh="卡面", ja="カード") # for asset command (implying plural)
    character = _("character", zh="角色", ja="キャラクター")
    character_event_chart = _("character_event_chart", zh_TW="角色活動排名圖", zh_CN="角色活动排名图", ja="応援イベントランキング推移")
    character_event_pt = _("character_event_pt", zh_TW="角色活動得分", zh_CN="角色活动得分", ja="応援イベント得点")
    chart = _("chart", zh_TW="譜面", zh_CN="谱面", ja="譜面")
    chart_video = _("chart_video", zh_TW="譜面影片", zh_CN="谱面影片")
    circle = _("circle", ja="サークル", zh_TW="社團", zh_CN="社团")
    count = _("count", zh_TW="數量", zh_CN="数量")
    cover_songs = _('cover_songs', zh="翻唱曲", ja="カバー曲") # vs pre_existing_songs
    detail = _("detail", zh_TW="詳細", zh_CN="详细", ja="詳細")
    diff = _("diff", zh_TW="難度", zh_CN="难度", ja="難易度")
    diff_summary = _('diff_summary', zh_TW="差異_概要", zh_CN="差异_概要")
    diff_table = _("diff-table", zh_TW="難度表", zh_CN="难度表")
    difference = _('diff', zh_TW="差異", zh_CN="差异")
    duration = _("duration", zh_TW="長度", zh_CN="长度", ja="長さ")
    efficient_songs = _("efficient_songs", zh="效率曲", ja="効率曲")
    episode = _('episode', zh_TW="話數", zh_CN="话数")
    event = _("event", zh_TW="活動", zh_CN="活动", ja="イベント")
    event_active = _("event_active", zh="活動_活躍人數", ja="イベント-アクティブ")
    event_active_character = _("event_active-character", zh="活動_活躍人數-角色", ja="イベント-アクティブ-キャラクター")
    event_character = _("event-character", zh_TW="活動-角色", zh_CN="活动-角色", ja="イベント-キャラクター")
    event_borders = _("event_borders", zh_TW="活動榜線", zh_CN="活动榜线", ja="イベントボーダー")
    event_borders_character = _("event_borders-character", zh_TW="活動榜線-角色", zh_CN="活动榜线-角色", ja="イベントボーダー-キャラクター")
    event_chart = _("event_chart", zh_TW="活動排名圖", zh_CN="活动排名图", ja="イベントランキング推移")
    event_chart_character = _("event_chart-character", zh_TW="活動排名圖-角色", zh_CN="活动排名图-角色", ja="イベントランキング推移-キャラクター")
    event_name = _('event_name', zh_TW="活動名稱", zh_CN="活动名称", ja="イベント名")
    event_pt = _("event_pt", zh_TW="活動得分", zh_CN="活动得分", ja="イベント得点")
    event_song = _("event_song", zh_TW="活動曲", zh_CN="活动曲", ja="イベント曲")
    file = _('file', zh_TW="檔案", zh_CN="档案", ja="ファイル")
    fps = _("fps", zh="fps", ja="fps")
    from_rank = _('from_rank', zh_TW="開始排名", zh_CN="开始排名")
    gacha = _("gacha", zh_TW="卡池", zh_CN="卡池", ja="ガチャ")
    gacha_name = _('gacha_name', zh_TW="卡池名稱", zh_CN="卡池名称", ja="ガチャ名")
    grayscale = _('grayscale', zh_TW="灰階", zh_CN="灰阶")
    guess_jacket = _("guess_jacket", zh="猜封面")
    guess_lyrics = _("guess_lyrics", zh_TW="猜歌詞", zh_CN="猜歌词")
    guess_silhouette = _("guess_silhouette", zh="猜剪影")
    guess_song = _("guess_song", zh="猜歌曲")
    hidden_fields = _("hidden_fields", zh_TW="隱藏欄位", zh_CN="隐藏栏位", ja="隠し項目")
    id = _("id", zh="id", ja="id")
    info = _("info", zh_TW="資訊", zh_CN="资讯", ja="情報")
    info_legacy = _("info_legacy", zh_TW="資訊_舊版", zh_CN="资讯_旧版", ja="情報_レガシー")
    keyboard = _('keyboard', zh_TW="鍵盤", zh_CN="键盘", ja="キーボード")
    keywords = _('keywords', zh_TW="關鍵字", zh_CN="关键字", ja="キーワード")
    latest = _('latest', zh="最近", ja="最近")
    latest_batch = _("latest_batch", zh="最新批次")
    list_ = _("list", zh="列表")
    lrc = _('lrc', zh="lrc")
    lyrics = _("lyrics", zh_TW="歌詞", zh_CN="歌词", ja="歌詞")
    master = _('master', zh="master")
    master_diff = _('master_diff', zh_TW="master_差異", zh_CN="master_差异")
    merge = _("merge", zh_TW="合併", zh_CN="合并") # option for merging multiple assets into one
    mirror = _("mirror", zh_TW="鏡像", zh_CN="镜像", ja="ミラー")
    mode = _("mode", zh="模式", ja="モード")
    name = _('name', zh_TW="名稱", zh_CN="名称", ja="名")
    next_rank = _("next_rank", zh="下一名", ja="次の順位")
    ping = "ping"
    player = _("player", zh="玩家", ja="プレーヤー")
    point = _('point', zh="point", ja="ポイント")
    poster = _('poster', zh_TW="海報", zh_CN="海报", ja="ポスター")
    posters = _('posters', zh_TW="海報", zh_CN="海报", ja="ポスター") # for asset command (implying plural)
    predict = _("predict", zh_TW="預測", zh_CN="预测", ja="予測")
    predict_detail = _("predict_detail", zh_TW="詳細預測", zh_CN="详细预测")
    predict_detail_character = _("predict_detail-character", zh_TW="詳細預測-角色", zh_CN="详细预测-角色")
    predict_detail_jiiku = _("predict_detail_jiiku", zh_TW="詳細預測_jiiku", zh_CN="详细预测_jiiku")
    predict_detail_character_jiiku = _("predict_detail-character_jiiku", zh_TW="詳細預測-角色_jiiku", zh_CN="详细预测-角色_jiiku")
    old_version = _("old_version", zh_TW="舊版本", zh_CN="旧版本")
    order = _('order', zh="次序")
    pre_existing_songs = _('existing_songs', zh="既存曲", ja="既存曲") # vs cover songs
    rank = _('rank', zh="排名", ja="順位") # as field name
    ranking = _("ranking", zh="排名", ja="ランキング") # as group name
    rarity = _('rarity', zh="稀有度", ja="レア度")
    rarity_katakana = _('rarity', zh="稀有度", ja="レアリティ") # same as rarity, but in katakana
    raw = _("raw", zh_TW="原始檔", zh_CN="原始档")
    recent = _("recent", zh="最近", ja="最近")
    recent_vocal = _("recent_vocal", zh="最近vocal")
    reencode = _("reencode", zh_TW="重新編碼", zh_CN="重新编码")
    reverse_song = _('reverse', zh="倒播")
    score = _('score', zh_TW="分數", zh_CN="分数", ja="スコア")
    score_approx = _('approx_score', zh_TW="預測分數", zh_CN="预测分数", ja="想定スコア")
    search = _('search', zh_TW="搜尋", zh_CN="搜索", ja="検索")
    secsep = _('secsep', zh_TW="秒數分隔", zh_CN="秒数分隔")
    size = _("size", zh_TW="尺寸", zh_CN="尺寸", ja="サイズ")
    show_character = _("show_character", zh_TW="顯示角色", zh_CN="显示角色")
    show_count = _('show_count', zh_TW="顯示數量", zh_CN="显示数量")
    show_distance = _("show_distance", zh_TW="顯示距離", zh_CN="显示距离")
    show_lyrics = _('show_lyrics', zh_TW="顯示歌詞", zh_CN="显示歌词")
    show_name = _("show_name", zh_TW="顯示名稱", zh_CN="显示名称")
    show_percentage = _("show_percentage", zh_TW="顯示百分比", zh_CN="显示百分比")
    song = _("song", zh="歌曲", ja="楽曲")
    song_discover = _('song_discover', zh="歌曲_探索")
    song_jackets = _('song_jackets', zh="歌曲封面") # for asset command (implying plural)
    song_name = _("song_name", zh="歌名", ja="曲名")
    sort_skill = _('sort_skill', zh="特技排序")
    source = _("source", zh_TW="來源", zh_CN="来源")
    speed = _("speed", zh="速度", ja="速度")
    spoiler = _("spoiler", zh_TW="劇透", zh_CN="剧透", ja="ネタバレ")
    stage = _("stage", zh_TW="關卡", zh_CN="关卡")
    stamps = _('stamps', zh_TW="貼圖", zh_CN="贴图", ja="スタンプ") # as asset command name (plural)
    stat = _("stat", zh_TW="統計", zh_CN="统计", ja="統計")
    static = _("static", zh_TW="靜態", zh_CN="静态", ja="静的")
    story = _('story', zh_TW="劇情", zh_CN="剧情", ja="ストリー")
    story_commu = _('story', zh_TW="劇情", zh_CN="剧情", ja="コミュ") # story, but using the phrase コミュ
    table_name = _("table_name", zh_TW="表格名稱", zh_CN="表格名称")
    type_ = _('type', zh_TW="種類", zh_CN="种类", ja="タイプ") # e.g. ranking type
    unreleased = _("unreleased", zh_TW="未公開", zh_CN="未公开", ja="未公開")
    ver_lang = _('ver', zh="版本") # usually for game version (e.g. en / kr)
    version = _("version", zh="版本", ja="バージョン")
    zipped = _("zipped", zh_TW="壓縮", zh_CN="压缩", ja="圧縮")

class gamename:
    """
    Used for command group name
    For game name in outputs, check GameNameGlossary
    """
    cgss = _("cgss", zh="cgss", ja="デレステ")
    mltd = _("mltd", zh="mltd", ja="ミリシタ")
    mobamas = _("mobamas", zh="cg走路工", ja="デレマス")
    gkms = _("gkms", zh_TW="學園偶大", zh_CN="学园偶大", ja="学マス")
    ipr = _("ipr", zh_TW="偶像榮耀", zh_CN="偶像荣耀", ja="アイプラ")
    llll = _("llll", zh="llll", ja="リンクラ")
    pjsk = _("pjsk", zh="pjsk", ja="プロセカ", ko="프로세카")
    pjsk_ = _("pjsk_", zh="pjsk_", ja="プロセカ_")
    rst = _("rst", zh="rst", ja="リステップ")
    rst_ = _("rst_", zh="rst_", ja="リステップ_")
    sc = _("sc", zh_TW="閃耀色彩", zh_CN="闪耀色彩", ja="シャニマス")
    sfp = _("sfp", zh="sfp", ja="シャニソン")
    wds = _("wds", zh="wds", ja="ユメステ")
    wds_ = _("wds_", zh="wds_", ja="ユメステ_")